## Assignment: Caching the Inverse of a Matrix
## Matrix inversion is usually a costly computation and there may be some 
# benefit to caching the inverse of a matrix rather than compute it repeatedly.
# Here, I define two functions to store a matrix m and cache's its inverse im.
# I assume that m is an invertible matrix, i.e. det(m)!=0.

## makeCacheMatrix: creates a special "matrix" object and cache its inverse.
##
## cacheSolve: computes the inverse of the special "matrix" returned by 
##               makeCacheMatrix. If the inverse has already been calculated, 
##               then the cachesolve should retrieve  the inverse from the cache.


## makeCacheMatrix set and get m and its inverse im

makeCacheMatrix <- function(m = matrix()) {
        im <- NULL        # initialize the inverse matrix to NULL

    #set and get functions for the matrix object
        set <- function(y) {            
                m <<- y
                im <<- NULL
                }
        get <- function() m
        
    #set and get function for the inverse matrix
        setinverse <- function(inverse){
                im <<- inverse
        } 
        getinverse <- function() im
        
        list(set = set, 
             get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## cacheSolve checks if the inverse has already been calculated: 
##       1)  it returns the value stored in cache, if im was already calculated, 
##       2)  else, it computes the inverse matrix and then it stores im in cache.

cacheSolve <- function(m, ...) {
        im <- m$getinverse() # take im generated by makeCacheMatrix
        
  ## check if im has already been calculated or is the NULL value from makeCacheMatrix
        if (!is.null(im)){
                ## get it from the cache
                print("cached data")
                return(im)
        }
        
  ## if im does'n exist, calculates the inverse and stores it in cache
        data <- m$get()
        im <- solve(data, ...)
        m$setinverse(im)
  ## print that are new data and the inverse matrix
        print("new data")
        im
}
